name: Build PvZ Mod Loader

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake (Force 32-bit)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -A Win32

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PvZ-Mod-Kit-x86
        path: |
          build/Release/version.dll
          build/Release/PvZ_Core.dll